In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\Dell\Documents\Project\Dataset\netflix_titles.csv")

In [3]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [4]:
data.shape

(6234, 12)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [6]:
data.isnull().sum()

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [7]:
data['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

In [12]:
d1=data[data['release_year']==2020]

In [14]:
d1.shape

(25, 12)

In [15]:
d1.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3180,81214114,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3195,80233408,Movie,"Live Twice, Love Once",Maria Ripoll,"Oscar Martínez, Inma Cuesta, Mafalda Carbonell...",Spain,"January 7, 2020",2020,TV-MA,102 min,"Comedies, Dramas, International Movies",When Emilio (Oscar Martínez) is diagnosed with...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...

In [16]:
data[
    (data['type']=='Movie')&
    (data['release_year']==2020)
]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3180,81214114,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...
3195,80233408,Movie,"Live Twice, Love Once",Maria Ripoll,"Oscar Martínez, Inma Cuesta, Mafalda Carbonell...",Spain,"January 7, 2020",2020,TV-MA,102 min,"Comedies, Dramas, International Movies",When Emilio (Oscar Martínez) is diagnosed with...
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,TV-14,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3352,81127902,Movie,A Fall from Grace,Tyler Perry,"Crystal Fox, Phylicia Rashad, Cicely Tyson, Br...",NaN,"January 17, 2020",2020,TV-MA,121 min,"Dramas, Thrillers","When gentle, law-abiding Grace confesses to ki..."
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,TV-MA,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3518,81088083,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."

In [17]:
data[data['director'].str.contains("Christopher Nolan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3524,70131314,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."

In [18]:
data[data['cast'].str.contains("Shah Rukh Khan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
533,81121023,Movie,My Next Guest with David Letterman and Shah Ru...,Michael Steed,"Shah Rukh Khan, David Letterman",NaN,"October 25, 2019",2019,TV-PG,61 min,International Movies,"""King of Bollywood"" Shah Rukh Khan opens up ab..."
1649,80164778,Movie,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiq...",India,"May 26, 2017",2017,NR,143 min,"Action & Adventure, Dramas, International Movies",After street smart kid Raees rises to become G...
1686,81005364,Movie,Zero,Aanand Rai,"Shah Rukh Khan, Anushka Sharma, Katrina Kaif, ...",India,"May 21, 2019",2018,TV-14,159 min,"Comedies, Dramas, International Movies",Through his relationships with two wildly diff...
1761,80157133,Movie,Chamatkar,Rajiv Mehra,"Shah Rukh Khan, Naseeruddin Shah, Urmila Maton...",India,"May 15, 2017",1992,TV-14,164 min,"Comedies, International Movies, Sci-Fi & Fantasy",A village schoolteacher and the ghost of a mur...
1764,80157083,Movie,Kabhi Haan Kabhi Naa,Kundan Shah,"Shah Rukh Khan, Suchitra Krishnamoorthi, Deepa...",India,"May 15, 2017",1994,TV-14,151 min,"Comedies, Dramas, International Movies",A dreamer falls for a girl who is in love with...
1767,24081514,Movie,Ram Jaane,Rajiv Mehra,"Shah Rukh Khan, Juhi Chawla, Vivek Mushran, Pa...",India,"May 15, 2017",1995,TV-14,142 min,"Dramas, International Movies, Music & Musicals","Two boyhood pals – one righteous, the other a ..."
1884,80158395,Movie,Chaahat,Mahesh Bhatt,"Naseeruddin Shah, Shah Rukh Khan, Pooja Bhatt,...",India,"May 1, 2017",1996,NR,148 min,"Dramas, International Movies, Romantic Movies",A vulnerable singer is forced to choose betwee...
1890,20764666,Movie,English Babu Desi Mem,Praveen Nischol,"Shah Rukh Khan, Sonali Bendre, Rajeshwari, Sae...",India,"May 1, 2017",1996,TV-14,163 min,"Comedies, Dramas, International Movies","After his brother dies, wealthy Vikram relucta..."
2216,60021758,Movie,Asoka,Santosh Sivan,"Shah Rukh Khan, Kareena Kapoor, Danny Denzongp...",India,"March 15, 2017",2001,R,168 min,"Action & Adventure, Dramas, International Movies",This elaborate Bollywood epic dramatizes one m...
2221,80156935,Movie,One 2 Ka 4,Shashilal K. Nair,"Shah Rukh Khan, Juhi Chawla, Jackie Shroff, Ni...",India,"March 15, 2017",2001,TV-14,160 min,"Action & Adventure, Comedies, Dramas","When his partner is killed, a young cop is for..."
2335,17671454,Movie,Dil Se,Mani Ratnam,"Shah Rukh Khan, Manisha Koirala, Preity Zinta,...",India,"March 1, 2018",1998,TV-14,166 min,"Dramas, International Movies, Romantic Movies",A radio broadcaster's intense attraction to a ...
2363,80059049,Movie,Pardes,Subhash Ghai,"Shah Rukh Khan, Amrish Puri, Mahima Chaudhry, ...",India,"March 1, 2018",1997,TV-14,187 min,"Dramas, International Movies, Romantic Movies","Prompted by loyalty, Arjun plays matchmaker be..."
2370,60035875,Movie,Shakti: The Power,Krishna Vamshi,"Karisma Kapoor, Nana Patekar, Sanjay Kapoor, S...",India,"March 1, 2018",2002,TV-MA,168 min,"Dramas, International Movies, Thrillers",A young mother must break free of the clutches...
2379,70019491,Movie,Swades,Ashutosh Gowariker,"Shah Rukh Khan, Gayatri Joshi, Kishori Balal, ...",India,"March 1, 2018",2004,TV-PG,185 min,"Dramas, International Movies",An Americanized NASA scientist returns to his ...
2394,20717860,Movie,Trimurti,Mukul Anand,"Anil Kapoor, Shah Rukh Khan, Jackie Shroff, Sa...",India,"March 1, 2018",1995,TV-PG,173 min,"Action & Adventure, Dramas, International Movies","After being framed, a policewoman languishing ..."
2742,70057994,Movie,Maya Memsaab,Ketan Mehta,"Deepa Sahi, Farooq Shaikh, Raj Babbar, Shah Ru...","France, United Kingdom, India","June 1, 2017",1993,NR,122 min,"Dramas, International Movies, Music & Musicals","A beautiful, wealthy woman’s insatiable appeti..."
2746,80156937,Movie,Oh Darling Yeh Hai India,Ketan Mehta,"Shah Rukh Khan, Deepa Sahi, Javed Jaffrey, Anu...",India,"June 1, 2017",1995,TV-14,154 min,"Action & Adventure, Comedies, International Mo...",A penniless actor new to Mumbai and a beautifu...
3096,60036112,Movie,Chalte Chalte,Aziz Mirza,"Shah Rukh Khan, Rani Mukerji, Jas Arora, Satis...",India,"July 1, 2018",2003,TV-PG,166 min,"Dramas, International Movies, Romantic Movies",Priya and Raj are polar opposites. Raj is bras...
4067,80091866,Movie,Dilwale,Rohit Shetty,"Shah Rukh Khan, Kajol, Kriti Sanon, Kabir Bedi...",India,"February 1, 2017",2015,TV-14,154 min,"Action & Adventure, Dramas, International Movies","A young couple falls in love, but conflicting ..."
4069,80017528,Movie,Happy New Year,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Abhishek Bac...",India,"February 1, 2017",2014,TV-14,179 min,"Action & Adventure, Comedies, Dramas",A revenge-seeking diamond thief gathers a ragt...
4432,80206847,Movie,Jab Harry Met Sejal,Imtiaz Ali,"Shah Rukh Khan, Anushka Sharma, Aru Krishansh ...",India,"December 2, 2017",2017,TV-14,142 min,"Comedies, International Movies, Romantic Movies",A philandering tour guide in Europe begins to ...
4491,70059026,Movie,Don,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Arjun Rampal,...",India,"December 15, 2019",2006,TV-MA,169 min,"Action & Adventure, International Movies",A ruthless crime boss and drug lord is nabbed ...
4492,70224999,Movie,Don 2,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal..."
4792,70254350,Movie,Chennai Express,Rohit Shetty,"Shah Rukh Khan, Deepika Padukone, Nikitin Dhee...",India,"August 31, 2018",2013,TV-14,135 min,"Action & Adventure, Comedies, International Mo...",What could have been a sad journey turns joyfu...
5308,80158042,Movie,Dear Zindagi,Gauri Shinde,"Alia Bhatt, Shah Rukh Khan, Ira Dubey, Yashasw...",India,"April 25, 2017",2016,TV-PG,149 min,"Comedies, Dramas, International Movies",A young cinematographer with a bright professi...
5513,70115621,Movie,Billu,Priyadarshan,"Irrfan Khan, Shah Rukh Khan, Lara Dutta, Rajpa...",India,"April 1, 2018",2009,TV-PG,132 min,"Dramas, International Movies",An Indian village is abuzz with news that a ma...
5531,70000196,Movie,Main Hoon Na,Farah Khan,"Shah Rukh Khan, Sunil Shetty, Sushmita Sen, Za...",India,"April 1, 2018",2004,TV-14,171 min,"Action & Adventure, Comedies, Dramas",Major Ram Prasad Sharma yearns to see project ...
5534,70083535,Movie,Om Shanti Om,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Shreyas Talp...",India,"April 1, 2018",2007,TV-14,169 min,"Comedies, Dramas, International Movies",Reincarnated 30 years after being killed in a ...
5535,70039405,Movie,Paheli,Amol Palekar,"Shah Rukh Khan, Rani Mukerji, Anupam Kher, Dil...",India,"April 1, 2018",2005,TV-PG,134 min,"Dramas, International Movies, Romantic Movies",Traditional Indian folklore comes alive in thi...
5536,60000722,Movie,Phir Bhi Dil Hai Hindustani,Aziz Mirza,"Shah Rukh Khan, Juhi Chawla, Paresh Rawal, Sat...",India,"April 1, 2018",2000,TV-PG,159 min,"Comedies, Dramas, International Movies","In this Bollywood entertainment, two journalis..."

In [22]:
data['country'].isnull().sum()

np.int64(0)

In [ ]:
data['country'] = data['country'].fillna("Unknown")

0       United States, India, South Korea, China
1                                 United Kingdom
2                                  United States
3                                  United States
4                                  United States
                          ...
6229                               United States
6230                               United States
6231                                     Unknown
6232                              United Kingdom
6233                               United States
Name: country, Length: 6234, dtype: str

In [23]:
data[data['country'].str.contains("Unknown")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,80169755,Movie,Joaquín Reyes: Una y no más,José Miguel Contreras,Joaquín Reyes,Unknown,"September 8, 2017",2017,TV-MA,78 min,Stand-Up Comedy,Comedian and celebrity impersonator Joaquín Re...
12,80182480,Movie,Krish Trish and Baltiboy,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2009,TV-Y7,58 min,Children & Family Movies,"A team of minstrels, including a monkey, cat a..."
13,80182483,Movie,Krish Trish and Baltiboy: Battle of Wits,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2013,TV-Y7,62 min,Children & Family Movies,"An artisan is cheated of his payment, a lion o..."
14,80182596,Movie,Krish Trish and Baltiboy: Best Friends Forever,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Deepak...",Unknown,"September 8, 2017",2016,TV-Y,65 min,Children & Family Movies,"A cat, monkey and donkey team up to narrate fo..."
15,80182482,Movie,Krish Trish and Baltiboy: Comics of India,Tilak Shetty,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2012,TV-Y7,61 min,Children & Family Movies,"In three comic-strip-style tales, a boy tries ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6170,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",Unknown,"August 14, 2017",2010,TV-PG,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6195,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",Unknown,"April 27, 2018",2016,TV-14,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6199,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",Unknown,"April 23, 2019",2016,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,Unknown,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,Unknown,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

In [25]:
data['country'].nunique()

555

In [30]:
d2=data[
    (data['type']=='Movie')&
    (data['country']=='India')&
    (data['release_year']==2019)
]

In [31]:
d2.shape

(49, 12)

In [32]:
d2.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
35,81154455,Movie,Article 15,Anubhav Sinha,"Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud...",India,"September 6, 2019",2019,TV-MA,125 min,"Dramas, International Movies, Thrillers",The grim realities of caste discrimination com...
58,81155784,Movie,Watchman,A. L. Vijay,"G.V. Prakash Kumar, Samyuktha Hegde, Suman, Ra...",India,"September 4, 2019",2019,TV-14,93 min,"Comedies, Dramas, International Movies","Rushing to pay off a loan shark, a young man b..."
109,81177238,Movie,Malaal,Mangesh Hadawale,"Meezaan Jaffrey, Sharmin Segal, Chinmaya Surve...",India,"September 26, 2019",2019,TV-14,133 min,"International Movies, Romantic Movies",Class divides become thorns in the budding rom...
119,81186758,Movie,Oh! Baby (Malayalam),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...
120,81186757,Movie,Oh! Baby (Tamil),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...