In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\Dell\Documents\Project\Dataset\netflix_titles.csv")

In [3]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [6]:
data['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

In [7]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [8]:
data['release_year'].max()

np.int64(2020)

In [9]:
data['release_year'].min()

np.int64(1925)

In [10]:
data[data['release_year']==2020]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3180,81214114,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3195,80233408,Movie,"Live Twice, Love Once",Maria Ripoll,"Oscar Martínez, Inma Cuesta, Mafalda Carbonell...",Spain,"January 7, 2020",2020,TV-MA,102 min,"Comedies, Dramas, International Movies",When Emilio (Oscar Martínez) is diagnosed with...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3221,80237347,TV Show,Go! Go! Cory Carson,NaN,"Alan C. Lim, Paul Killam, Maisie Benson, Kerry...",United States,"January 4, 2020",2020,TV-Y,1 Season,Kids' TV,"Beep, beep – go, go! Buckle up for fun and adv..."
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,TV-14,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3325,81160763,TV Show,"Sex, Explained",NaN,Janelle Monáe,United States,"January 2, 2020",2020,TV-MA,1 Season,"Docuseries, Science & Nature TV",From the biology of attraction to the history ...
3352,81127902,Movie,A Fall from Grace,Tyler Perry,"Crystal Fox, Phylicia Rashad, Cicely Tyson, Br...",NaN,"January 17, 2020",2020,TV-MA,121 min,"Dramas, Thrillers","When gentle, law-abiding Grace confesses to ki..."
3353,80995039,TV Show,Ares,NaN,"Jade Olieberg, Tobias Kersloot, Lisa Smit, Fri...",NaN,"January 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","Aiming to become part of Amsterdam's elite, an..."
3354,81062580,TV Show,Nailed It! Germany,NaN,"Angelina Kirsch, Bernd Siefert",NaN,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
3363,80996973,TV Show,Handsome Siblings,NaN,"Hu Yitian, Chen Zheyuan, Liang Jie, Vicky Lian...",China,"January 16, 2020",2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",Clashing martial arts twins face relentless vi...
3379,81062828,TV Show,Killer Inside: The Mind of Aaron Hernandez,NaN,Aaron Hernandez,United States,"January 15, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries","Via interviews with friends, players and insid..."
3426,80221553,TV Show,Kipo and the Age of Wonderbeasts,NaN,"Karen Fukuhara, Sydney Mikayla, Deon Cole, Coy...",United States,"January 14, 2020",2020,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",Making her way through a world of mutant anima...
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,TV-MA,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,TV-G,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
3464,80237329,TV Show,AJ and the Queen,NaN,"RuPaul Charles, Izzy G., Michael-Leon Wooley, ...",United States,"January 10, 2020",2020,TV-14,1 Season,"TV Comedies, TV Dramas",While traveling across the country in a run-do...
3466,81183491,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,"Amit Sial, Dibyendu Bhattacharya, Aksha Pardha...",India,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A group of small-town young men run a lucrativ...
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3472,81074060,TV Show,Until Dawn,NaN,"Ahmed Sylla, Alban Ivanov, Ornella Fleury, Nat...",France,"January 10, 2020",2020,TV-MA,1 Season,"International TV Shows, Reality TV, TV Comedies",France’s funniest comics carry out ghastly tas...
3518,81088083,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."
3541,80117557,TV Show,Messiah,NaN,"Michelle Monaghan, Mehdi Dehbi, John Ortiz, To...",United States,"January 1, 2020",2020,TV-MA,1 Season,"TV Dramas, TV Thrillers",A wary CIA officer investigates a charismatic ...
3546,80197991,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,NaN,"January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
3562,80201590,TV Show,Spinning Out,NaN,"Kaya Scodelario, January Jones, Will Kemp, Wil...",NaN,"January 1, 2020",2020,TV-MA,1 Season,TV Dramas,A figure skating Olympic hopeful struggles to ...
3573,81044551,TV Show,The Circle,NaN,Michelle Buteau,NaN,"January 1, 2020",2020,TV-MA,1 Season,Reality TV,Status and strategy collide in this social exp...

In [11]:
data[data['release_year']==1925]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4292,81030762,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-PG,1 Season,TV Shows,This collection restores films from women who ...

In [12]:
data['director'].isnull().sum()

np.int64(1969)

In [13]:
data[data['cast'].str.contains("Shah Rukh Khan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
533,81121023,Movie,My Next Guest with David Letterman and Shah Ru...,Michael Steed,"Shah Rukh Khan, David Letterman",NaN,"October 25, 2019",2019,TV-PG,61 min,International Movies,"""King of Bollywood"" Shah Rukh Khan opens up ab..."
1649,80164778,Movie,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiq...",India,"May 26, 2017",2017,NR,143 min,"Action & Adventure, Dramas, International Movies",After street smart kid Raees rises to become G...
1686,81005364,Movie,Zero,Aanand Rai,"Shah Rukh Khan, Anushka Sharma, Katrina Kaif, ...",India,"May 21, 2019",2018,TV-14,159 min,"Comedies, Dramas, International Movies",Through his relationships with two wildly diff...
1761,80157133,Movie,Chamatkar,Rajiv Mehra,"Shah Rukh Khan, Naseeruddin Shah, Urmila Maton...",India,"May 15, 2017",1992,TV-14,164 min,"Comedies, International Movies, Sci-Fi & Fantasy",A village schoolteacher and the ghost of a mur...
1764,80157083,Movie,Kabhi Haan Kabhi Naa,Kundan Shah,"Shah Rukh Khan, Suchitra Krishnamoorthi, Deepa...",India,"May 15, 2017",1994,TV-14,151 min,"Comedies, Dramas, International Movies",A dreamer falls for a girl who is in love with...
1767,24081514,Movie,Ram Jaane,Rajiv Mehra,"Shah Rukh Khan, Juhi Chawla, Vivek Mushran, Pa...",India,"May 15, 2017",1995,TV-14,142 min,"Dramas, International Movies, Music & Musicals","Two boyhood pals – one righteous, the other a ..."
1884,80158395,Movie,Chaahat,Mahesh Bhatt,"Naseeruddin Shah, Shah Rukh Khan, Pooja Bhatt,...",India,"May 1, 2017",1996,NR,148 min,"Dramas, International Movies, Romantic Movies",A vulnerable singer is forced to choose betwee...
1890,20764666,Movie,English Babu Desi Mem,Praveen Nischol,"Shah Rukh Khan, Sonali Bendre, Rajeshwari, Sae...",India,"May 1, 2017",1996,TV-14,163 min,"Comedies, Dramas, International Movies","After his brother dies, wealthy Vikram relucta..."
2216,60021758,Movie,Asoka,Santosh Sivan,"Shah Rukh Khan, Kareena Kapoor, Danny Denzongp...",India,"March 15, 2017",2001,R,168 min,"Action & Adventure, Dramas, International Movies",This elaborate Bollywood epic dramatizes one m...
2221,80156935,Movie,One 2 Ka 4,Shashilal K. Nair,"Shah Rukh Khan, Juhi Chawla, Jackie Shroff, Ni...",India,"March 15, 2017",2001,TV-14,160 min,"Action & Adventure, Comedies, Dramas","When his partner is killed, a young cop is for..."
2335,17671454,Movie,Dil Se,Mani Ratnam,"Shah Rukh Khan, Manisha Koirala, Preity Zinta,...",India,"March 1, 2018",1998,TV-14,166 min,"Dramas, International Movies, Romantic Movies",A radio broadcaster's intense attraction to a ...
2363,80059049,Movie,Pardes,Subhash Ghai,"Shah Rukh Khan, Amrish Puri, Mahima Chaudhry, ...",India,"March 1, 2018",1997,TV-14,187 min,"Dramas, International Movies, Romantic Movies","Prompted by loyalty, Arjun plays matchmaker be..."
2370,60035875,Movie,Shakti: The Power,Krishna Vamshi,"Karisma Kapoor, Nana Patekar, Sanjay Kapoor, S...",India,"March 1, 2018",2002,TV-MA,168 min,"Dramas, International Movies, Thrillers",A young mother must break free of the clutches...
2379,70019491,Movie,Swades,Ashutosh Gowariker,"Shah Rukh Khan, Gayatri Joshi, Kishori Balal, ...",India,"March 1, 2018",2004,TV-PG,185 min,"Dramas, International Movies",An Americanized NASA scientist returns to his ...
2394,20717860,Movie,Trimurti,Mukul Anand,"Anil Kapoor, Shah Rukh Khan, Jackie Shroff, Sa...",India,"March 1, 2018",1995,TV-PG,173 min,"Action & Adventure, Dramas, International Movies","After being framed, a policewoman languishing ..."
2742,70057994,Movie,Maya Memsaab,Ketan Mehta,"Deepa Sahi, Farooq Shaikh, Raj Babbar, Shah Ru...","France, United Kingdom, India","June 1, 2017",1993,NR,122 min,"Dramas, International Movies, Music & Musicals","A beautiful, wealthy woman’s insatiable appeti..."
2746,80156937,Movie,Oh Darling Yeh Hai India,Ketan Mehta,"Shah Rukh Khan, Deepa Sahi, Javed Jaffrey, Anu...",India,"June 1, 2017",1995,TV-14,154 min,"Action & Adventure, Comedies, International Mo...",A penniless actor new to Mumbai and a beautifu...
3096,60036112,Movie,Chalte Chalte,Aziz Mirza,"Shah Rukh Khan, Rani Mukerji, Jas Arora, Satis...",India,"July 1, 2018",2003,TV-PG,166 min,"Dramas, International Movies, Romantic Movies",Priya and Raj are polar opposites. Raj is bras...
4067,80091866,Movie,Dilwale,Rohit Shetty,"Shah Rukh Khan, Kajol, Kriti Sanon, Kabir Bedi...",India,"February 1, 2017",2015,TV-14,154 min,"Action & Adventure, Dramas, International Movies","A young couple falls in love, but conflicting ..."
4069,80017528,Movie,Happy New Year,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Abhishek Bac...",India,"February 1, 2017",2014,TV-14,179 min,"Action & Adventure, Comedies, Dramas",A revenge-seeking diamond thief gathers a ragt...
4432,80206847,Movie,Jab Harry Met Sejal,Imtiaz Ali,"Shah Rukh Khan, Anushka Sharma, Aru Krishansh ...",India,"December 2, 2017",2017,TV-14,142 min,"Comedies, International Movies, Romantic Movies",A philandering tour guide in Europe begins to ...
4491,70059026,Movie,Don,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Arjun Rampal,...",India,"December 15, 2019",2006,TV-MA,169 min,"Action & Adventure, International Movies",A ruthless crime boss and drug lord is nabbed ...
4492,70224999,Movie,Don 2,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal..."
4792,70254350,Movie,Chennai Express,Rohit Shetty,"Shah Rukh Khan, Deepika Padukone, Nikitin Dhee...",India,"August 31, 2018",2013,TV-14,135 min,"Action & Adventure, Comedies, International Mo...",What could have been a sad journey turns joyfu...
5308,80158042,Movie,Dear Zindagi,Gauri Shinde,"Alia Bhatt, Shah Rukh Khan, Ira Dubey, Yashasw...",India,"April 25, 2017",2016,TV-PG,149 min,"Comedies, Dramas, International Movies",A young cinematographer with a bright professi...
5513,70115621,Movie,Billu,Priyadarshan,"Irrfan Khan, Shah Rukh Khan, Lara Dutta, Rajpa...",India,"April 1, 2018",2009,TV-PG,132 min,"Dramas, International Movies",An Indian village is abuzz with news that a ma...
5531,70000196,Movie,Main Hoon Na,Farah Khan,"Shah Rukh Khan, Sunil Shetty, Sushmita Sen, Za...",India,"April 1, 2018",2004,TV-14,171 min,"Action & Adventure, Comedies, Dramas",Major Ram Prasad Sharma yearns to see project ...
5534,70083535,Movie,Om Shanti Om,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Shreyas Talp...",India,"April 1, 2018",2007,TV-14,169 min,"Comedies, Dramas, International Movies",Reincarnated 30 years after being killed in a ...
5535,70039405,Movie,Paheli,Amol Palekar,"Shah Rukh Khan, Rani Mukerji, Anupam Kher, Dil...",India,"April 1, 2018",2005,TV-PG,134 min,"Dramas, International Movies, Romantic Movies",Traditional Indian folklore comes alive in thi...
5536,60000722,Movie,Phir Bhi Dil Hai Hindustani,Aziz Mirza,"Shah Rukh Khan, Juhi Chawla, Paresh Rawal, Sat...",India,"April 1, 2018",2000,TV-PG,159 min,"Comedies, Dramas, International Movies","In this Bollywood entertainment, two journalis..."

In [14]:
data[data['cast'].str.contains("Salman Khan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
576,70198040,Movie,Ready,Anees Bazmee,"Salman Khan, Asin, Paresh Rawal, Mahesh Manjre...",India,"October 22, 2017",2011,TV-PG,144 min,"Comedies, International Movies, Romantic Movies","Bollywood superstar Salman Khan plays Prem, an..."
1301,70040076,Movie,Lucky: No Time for Love,"Radhika Rao, Vinay Sapru","Salman Khan, Sneha Ullal, Mithun Chakraborty, ...",India,"November 15, 2017",2005,TV-14,131 min,"Dramas, International Movies, Romantic Movies","During an uprising in Russia's St. Petersburg,..."
1306,70260514,Movie,Mumbai Cha Raja,Manjeet Singh,"Rahul Bairagi, Arbaaz Khan, Tejas Parvatkar, D...",India,"November 15, 2016",2012,TV-14,77 min,"Dramas, Independent Movies, International Movies","This coming-of-age tale follows Rahul, a young..."
1737,20258084,Movie,Andaz Apna Apna,Rajkumar Santoshi,"Aamir Khan, Salman Khan, Raveena Tandon, Karis...",India,"May 16, 2018",1994,TV-PG,160 min,"Comedies, Cult Movies, International Movies",Broke and with no concrete plans for the futur...
2362,80223230,Movie,No Entry,Anees Bazmee,"Anil Kapoor, Salman Khan, Fardeen Khan, Bipash...",India,"March 1, 2018",2005,TV-PG,161 min,"Comedies, International Movies","After a prank goes sideways, three buddies fin..."
3657,60035870,Movie,Hum Aapke Hain Koun,Sooraj R. Barjatya,"Madhuri Dixit, Salman Khan, Mohnish Bahl, Renu...",India,"January 1, 2018",1994,NR,193 min,"Classic Movies, Dramas, International Movies","Although Nisha falls for Prem, she agrees to m..."
3658,80074065,Movie,Hum Saath-Saath Hain,Sooraj R. Barjatya,"Salman Khan, Karisma Kapoor, Saif Ali Khan, Ta...",India,"January 1, 2018",1999,TV-G,176 min,"Dramas, International Movies, Music & Musicals",A scheming matriarch plots to cut off her disa...
3665,19207412,Movie,Maine Pyar Kiya,Sooraj R. Barjatya,"Salman Khan, Bhagyashree, Alok Nath, Rajeev Ve...",India,"January 1, 2018",1989,TV-PG,192 min,"Dramas, International Movies, Music & Musicals",When the son of a wealthy businessman and the ...
4186,81213893,Movie,Chal Mere Bhai,David Dhawan,"Sanjay Dutt, Salman Khan, Karisma Kapoor, Dali...",India,"December 31, 2019",2000,TV-14,132 min,"Comedies, International Movies, Romantic Movies","When a secretary saves her tycoon boss's life,..."
4202,81213885,Movie,Jaan-E-Mann: Let's Fall in Love... Again,Shirish Kunder,"Salman Khan, Akshay Kumar, Preity Zinta, Anupa...",India,"December 31, 2019",2006,TV-14,163 min,"Dramas, International Movies, Romantic Movies","To avoid alimony payments, an aspiring actor s..."
4206,17457622,Movie,Judwaa,David Dhawan,"Salman Khan, Karisma Kapoor, Rambha, Kader Kha...",India,"December 31, 2019",1997,TV-14,133 min,"Comedies, International Movies, Romantic Movies","Separated at birth, a pair of identical twins ..."
4212,70040912,Movie,Maine Pyaar Kyun Kiya,David Dhawan,"Salman Khan, Sushmita Sen, Sohail Khan, Katrin...",India,"December 31, 2019",2005,TV-14,137 min,"Comedies, International Movies, Music & Musicals","After lying to his girlfriend, orthopedic surg..."
4214,70018445,Movie,Mujhse Shaadi Karogi,David Dhawan,"Rajpal Yadav, Amrish Puri, Kader Khan, Shashi ...",India,"December 31, 2019",2004,TV-PG,158 min,"Comedies, International Movies, Romantic Movies","Samir must overcome a hostile horoscope, a hot..."
4921,70114589,Movie,Main aurr Mrs. Khanna,Prem Soni,"Salman Khan, Kareena Kapoor, Sohail Khan, Prei...",India,"August 2, 2018",2009,TV-PG,109 min,"International Movies, Music & Musicals, Romant...",A financially troubled Indian man heads to Sin...

In [15]:
data[data['director'].str.contains("Christopher Nolan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3524,70131314,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."

In [18]:
data[data['director'].str.contains("James Cameron")]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [19]:
data['country'].value_counts()

country
United States                              2032
India                                       777
United Kingdom                              348
Japan                                       176
Canada                                      141
                                           ...
United States, Hungary, Ireland, Canada       1
Norway, Sweden                                1
United States, Mexico, Colombia               1
Italy, Germany                                1
Cyprus, Austria, Thailand                     1
Name: count, Length: 554, dtype: int64

In [20]:
data.shape

(6234, 12)

In [23]:
data['country'].isnull().sum()

np.int64(0)

In [22]:
data['country']= data['country'].fillna('Unknown')

In [24]:
data['country'].value_counts()

country
United States                              2032
India                                       777
Unknown                                     476
United Kingdom                              348
Japan                                       176
                                           ...
United States, Hungary, Ireland, Canada       1
Norway, Sweden                                1
United States, Mexico, Colombia               1
Italy, Germany                                1
Cyprus, Austria, Thailand                     1
Name: count, Length: 555, dtype: int64

In [26]:
data.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...