In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r'C:\Users\Dell\Documents\Project\Dataset\netflix_titles.csv')

In [5]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [7]:
data['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

In [8]:
data[data['release_year']==2020]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3180,81214114,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3195,80233408,Movie,"Live Twice, Love Once",Maria Ripoll,"Oscar Martínez, Inma Cuesta, Mafalda Carbonell...",Spain,"January 7, 2020",2020,TV-MA,102 min,"Comedies, Dramas, International Movies",When Emilio (Oscar Martínez) is diagnosed with...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3221,80237347,TV Show,Go! Go! Cory Carson,NaN,"Alan C. Lim, Paul Killam, Maisie Benson, Kerry...",United States,"January 4, 2020",2020,TV-Y,1 Season,Kids' TV,"Beep, beep – go, go! Buckle up for fun and adv..."
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,TV-14,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3325,81160763,TV Show,"Sex, Explained",NaN,Janelle Monáe,United States,"January 2, 2020",2020,TV-MA,1 Season,"Docuseries, Science & Nature TV",From the biology of attraction to the history ...
3352,81127902,Movie,A Fall from Grace,Tyler Perry,"Crystal Fox, Phylicia Rashad, Cicely Tyson, Br...",NaN,"January 17, 2020",2020,TV-MA,121 min,"Dramas, Thrillers","When gentle, law-abiding Grace confesses to ki..."
3353,80995039,TV Show,Ares,NaN,"Jade Olieberg, Tobias Kersloot, Lisa Smit, Fri...",NaN,"January 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","Aiming to become part of Amsterdam's elite, an..."
3354,81062580,TV Show,Nailed It! Germany,NaN,"Angelina Kirsch, Bernd Siefert",NaN,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
3363,80996973,TV Show,Handsome Siblings,NaN,"Hu Yitian, Chen Zheyuan, Liang Jie, Vicky Lian...",China,"January 16, 2020",2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",Clashing martial arts twins face relentless vi...
3379,81062828,TV Show,Killer Inside: The Mind of Aaron Hernandez,NaN,Aaron Hernandez,United States,"January 15, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries","Via interviews with friends, players and insid..."
3426,80221553,TV Show,Kipo and the Age of Wonderbeasts,NaN,"Karen Fukuhara, Sydney Mikayla, Deon Cole, Coy...",United States,"January 14, 2020",2020,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",Making her way through a world of mutant anima...
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,TV-MA,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,TV-G,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
3464,80237329,TV Show,AJ and the Queen,NaN,"RuPaul Charles, Izzy G., Michael-Leon Wooley, ...",United States,"January 10, 2020",2020,TV-14,1 Season,"TV Comedies, TV Dramas",While traveling across the country in a run-do...
3466,81183491,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,"Amit Sial, Dibyendu Bhattacharya, Aksha Pardha...",India,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A group of small-town young men run a lucrativ...
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3472,81074060,TV Show,Until Dawn,NaN,"Ahmed Sylla, Alban Ivanov, Ornella Fleury, Nat...",France,"January 10, 2020",2020,TV-MA,1 Season,"International TV Shows, Reality TV, TV Comedies",France’s funniest comics carry out ghastly tas...
3518,81088083,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."
3541,80117557,TV Show,Messiah,NaN,"Michelle Monaghan, Mehdi Dehbi, John Ortiz, To...",United States,"January 1, 2020",2020,TV-MA,1 Season,"TV Dramas, TV Thrillers",A wary CIA officer investigates a charismatic ...
3546,80197991,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,NaN,"January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
3562,80201590,TV Show,Spinning Out,NaN,"Kaya Scodelario, January Jones, Will Kemp, Wil...",NaN,"January 1, 2020",2020,TV-MA,1 Season,TV Dramas,A figure skating Olympic hopeful struggles to ...
3573,81044551,TV Show,The Circle,NaN,Michelle Buteau,NaN,"January 1, 2020",2020,TV-MA,1 Season,Reality TV,Status and strategy collide in this social exp...

In [4]:
data['country'].nunique()

554

In [8]:
data['country'].isnull().sum()

np.int64(0)

**Here we fill null values with unknown value**

In [7]:
data['country'] = data['country'].fillna('Unknown')

**Now here we are checking that all null values in coutry get replaced by unknow**

In [14]:
data[data['country'].str.contains('Unknown')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,80169755,Movie,Joaquín Reyes: Una y no más,José Miguel Contreras,Joaquín Reyes,Unknown,"September 8, 2017",2017,TV-MA,78 min,Stand-Up Comedy,Comedian and celebrity impersonator Joaquín Re...
12,80182480,Movie,Krish Trish and Baltiboy,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2009,TV-Y7,58 min,Children & Family Movies,"A team of minstrels, including a monkey, cat a..."
13,80182483,Movie,Krish Trish and Baltiboy: Battle of Wits,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2013,TV-Y7,62 min,Children & Family Movies,"An artisan is cheated of his payment, a lion o..."
14,80182596,Movie,Krish Trish and Baltiboy: Best Friends Forever,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Deepak...",Unknown,"September 8, 2017",2016,TV-Y,65 min,Children & Family Movies,"A cat, monkey and donkey team up to narrate fo..."
15,80182482,Movie,Krish Trish and Baltiboy: Comics of India,Tilak Shetty,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",Unknown,"September 8, 2017",2012,TV-Y7,61 min,Children & Family Movies,"In three comic-strip-style tales, a boy tries ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6170,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",Unknown,"August 14, 2017",2010,TV-PG,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6195,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",Unknown,"April 27, 2018",2016,TV-14,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6199,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",Unknown,"April 23, 2019",2016,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,Unknown,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,Unknown,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

**There are many actors in cast so we have to get only first actore so we are seprating by , and str[0] menas which here 0 means ist coma and in last we take all first actors and keep it in first column that we have created**

In [15]:
data['First_actor'] = data['cast'].str.split(',').str[0]

In [3]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

**oldest movies in this dataset**

In [9]:
data['release_year'].min()

np.int64(1925)

In [10]:
data['release_year'].max()

np.int64(2020)

In [6]:
data['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

**Here we filter tv shows that have een realsed in 2020**

In [7]:
data[(data['release_year']==2020)&
     (data['type']=='TV Show')
     ]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3221,80237347,TV Show,Go! Go! Cory Carson,NaN,"Alan C. Lim, Paul Killam, Maisie Benson, Kerry...",United States,"January 4, 2020",2020,TV-Y,1 Season,Kids' TV,"Beep, beep – go, go! Buckle up for fun and adv..."
3325,81160763,TV Show,"Sex, Explained",NaN,Janelle Monáe,United States,"January 2, 2020",2020,TV-MA,1 Season,"Docuseries, Science & Nature TV",From the biology of attraction to the history ...
3353,80995039,TV Show,Ares,NaN,"Jade Olieberg, Tobias Kersloot, Lisa Smit, Fri...",NaN,"January 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","Aiming to become part of Amsterdam's elite, an..."
3354,81062580,TV Show,Nailed It! Germany,NaN,"Angelina Kirsch, Bernd Siefert",NaN,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
3363,80996973,TV Show,Handsome Siblings,NaN,"Hu Yitian, Chen Zheyuan, Liang Jie, Vicky Lian...",China,"January 16, 2020",2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",Clashing martial arts twins face relentless vi...
3379,81062828,TV Show,Killer Inside: The Mind of Aaron Hernandez,NaN,Aaron Hernandez,United States,"January 15, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries","Via interviews with friends, players and insid..."
3426,80221553,TV Show,Kipo and the Age of Wonderbeasts,NaN,"Karen Fukuhara, Sydney Mikayla, Deon Cole, Coy...",United States,"January 14, 2020",2020,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",Making her way through a world of mutant anima...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,TV-G,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
3464,80237329,TV Show,AJ and the Queen,NaN,"RuPaul Charles, Izzy G., Michael-Leon Wooley, ...",United States,"January 10, 2020",2020,TV-14,1 Season,"TV Comedies, TV Dramas",While traveling across the country in a run-do...
3466,81183491,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,"Amit Sial, Dibyendu Bhattacharya, Aksha Pardha...",India,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A group of small-town young men run a lucrativ...
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3472,81074060,TV Show,Until Dawn,NaN,"Ahmed Sylla, Alban Ivanov, Ornella Fleury, Nat...",France,"January 10, 2020",2020,TV-MA,1 Season,"International TV Shows, Reality TV, TV Comedies",France’s funniest comics carry out ghastly tas...
3541,80117557,TV Show,Messiah,NaN,"Michelle Monaghan, Mehdi Dehbi, John Ortiz, To...",United States,"January 1, 2020",2020,TV-MA,1 Season,"TV Dramas, TV Thrillers",A wary CIA officer investigates a charismatic ...
3546,80197991,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,NaN,"January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
3562,80201590,TV Show,Spinning Out,NaN,"Kaya Scodelario, January Jones, Will Kemp, Wil...",NaN,"January 1, 2020",2020,TV-MA,1 Season,TV Dramas,A figure skating Olympic hopeful struggles to ...
3573,81044551,TV Show,The Circle,NaN,Michelle Buteau,NaN,"January 1, 2020",2020,TV-MA,1 Season,Reality TV,Status and strategy collide in this social exp...

In [9]:
data[
    (data['country']=='United States')&
    (data['type']=='TV Show')
]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
54,80113482,TV Show,No Tomorrow,NaN,"Joshua Sasse, Tori Anderson, Jonathan Langdon,...",United States,"September 5, 2017",2016,TV-14,1 Season,"Romantic TV Shows, TV Comedies, TV Dramas",Her straitjacketed life turned topsy-turvy by ...
61,80113641,TV Show,Frequency,NaN,"Peyton List, Riley Smith, Mekhi Phifer, Devin ...",United States,"September 4, 2017",2016,TV-14,1 Season,"Crime TV Shows, TV Dramas, TV Mysteries",A detective seizes a precious opportunity to c...
...,...,...,...,...,...,...,...,...,...,...,...,...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

**Here we get the number of movies that have been realsed each year**

In [10]:
data.groupby('release_year')['title'].count()

release_year
1925       1
1942       2
1943       3
1944       3
1945       3
        ...
2016     830
2017     959
2018    1063
2019     843
2020      25
Name: title, Length: 72, dtype: int64

In [11]:
data[data['title'].str.contains('Love')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
19,80057969,Movie,Love,Gaspar Noé,"Karl Glusman, Klara Kristin, Aomi Muyock, Ugo ...","France, Belgium","September 8, 2017",2015,NR,135 min,"Cult Movies, Dramas, Independent Movies",A man in an unsatisfying marriage recalls the ...
46,81016044,Movie,Bangkok Traffic (Love) Story,Adisorn Tresirikasem,"Theeradej Wongpuapan, Sirin Horwang, Ungsumaly...",Thailand,"September 5, 2018",2009,TV-14,126 min,"Comedies, International Movies, Romantic Movies",After an encounter with an engineer working th...
47,80158838,Movie,I Fine... Thank You... Love You,Mez Tharatorn,"Preechaya Pongthananikorn, Sunny Suwanmethanon...",Thailand,"September 5, 2018",2014,TV-14,116 min,"Comedies, International Movies, Romantic Movies",Desperate to go to the U.S. to win back his gi...
66,81011682,TV Show,Christiane Amanpour: Sex & Love Around the World,NaN,NaN,United States,"September 30, 2018",2018,TV-MA,1 Season,Docuseries,"A contextual, acculturated dive into how adult..."
74,80184358,TV Show,Lovesick,NaN,"Kongyingyong Chonlathorn, Phumphothingam Nawat...",NaN,"September 3, 2018",2014,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Love and academics get complicated at an all-m...
...,...,...,...,...,...,...,...,...,...,...,...,...
5848,80174280,TV Show,Ainori Love Wagon: Asian Journey,NaN,"Becky, Audrey, Mayuko Kawakita, Shimon Okura",Japan,"March 28, 2019",2018,TV-MA,2 Seasons,"International TV Shows, Reality TV, Romantic T...",Seven men and women board a pink bus in search...
5896,80993774,TV Show,Roonpi Secret Love,NaN,"Kanyawee Songmuang, Korapat Kirdpan",Thailand,"June 21, 2019",2016,TV-PG,3 Seasons,"International TV Shows, Romantic TV Shows, Tee...",High school senior Belle pursues a shy junior ...
5941,81026700,TV Show,My First First Love,NaN,"Ji Soo, Jung Chae-yeon, Jinyoung, Choi Ri, Kan...",South Korea,"July 26, 2019",2019,TV-PG,2 Seasons,"International TV Shows, Korean TV Shows, Roman...","Due to various personal reasons, a group of Yu..."
6026,80041601,TV Show,Lovesick,NaN,"Johnny Flynn, Antonia Thomas, Daniel Ings, Han...",United Kingdom,"January 1, 2018",2018,TV-MA,3 Seasons,"British TV Shows, International TV Shows, Roma...","In his quest for true love, Dylan found chlamy..."
6048,80126684,TV Show,Love Me As I Am,NaN,"Alper Saldıran, Zeynep Çamcı, Burcu Altın, Umu...",NaN,"February 22, 2017",2015,TV-14,3 Seasons,"International TV Shows, Romantic TV Shows, TV ...",After wealthy college boy Ömer and lower class...

In [13]:
data[data['director'].str.contains('Gaspar Noé')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
19,80057969,Movie,Love,Gaspar Noé,"Karl Glusman, Klara Kristin, Aomi Muyock, Ugo ...","France, Belgium","September 8, 2017",2015,NR,135 min,"Cult Movies, Dramas, Independent Movies",A man in an unsatisfying marriage recalls the ...

**so here we convert textual date into real date and str.strip mean that cut spaces dont keep any space between date**

In [11]:
data['date_added'] = pd.to_datetime(data['date_added'].str.strip())

In [12]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09-09,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09-08,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...